language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
env:
 - TOX_ENV=py37
 - TOX_ENV=docs
 - TOX_ENV=flake8
install:
 - pip install tox
script:
 - tox -e $TOX_ENV
